export interface Markets {
  name: string,
  enabled: boolean,
  postOnly: boolean,
  priceIncrement: number,
  sizeIncrement: number,
  minProvideSize: number,
  last: number,
  bid: number,
  ask: number,
  price: number | null,
  type: string,
  baseCurrency: string | null,
  quoteCurrency: string | null,
  underlying: string,
  restricted: boolean,
  highLeverageFeeExempt: boolean,
  largeOrderThreshold: number,
  change1h: number,
  change24h: number,
  changeBod: number,
  quoteVolume24h: number,
  volumeUsd24h: number
}
